# -*- coding: utf-8 -*-
"""tfs2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1obbdv761E_i16hIAwNBwfBajodLR14Y3
"""

# ==============================================================================
# CELDA 1 — CARGA DE DATOS Y PREPROCESADO  (versión corregida)
# ==============================================================================
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

# ── Config ───────────────────────────────────────────────────────────────────
INCLUIR_98D = True   # pon False si NO quieres el target de 98 días (solo 26 muestras)

# ── 1. Cargar (cabecera en fila 17) ──────────────────────────────────────────
nombre_archivo = '/content/drive/MyDrive/Base de datos Final.xlsx'
df_raw = pd.read_excel(nombre_archivo, header=17)

# ── 2. Renombrar columnas por posición ───────────────────────────────────────
rename_map = {
    df_raw.columns[0]:  'referencia',
    df_raw.columns[1]:  'material',
    df_raw.columns[2]:  'relacion_ac',
    df_raw.columns[3]:  'cemento',
    df_raw.columns[4]:  'tipo_acelerante',
    df_raw.columns[5]:  'acelerante',
    df_raw.columns[6]:  'dosificacion',
    df_raw.columns[7]:  'punto_max_ace_mWg',
    df_raw.columns[8]:  'pendiente_ace_mWgh',
    df_raw.columns[9]:  'energia_ace_Jg',
    df_raw.columns[10]: 'punto_max_ppal_mWg',
    df_raw.columns[11]: 'pendiente_ppal_mWgh',
    df_raw.columns[12]: 'energia_ppal_Jg',
    df_raw.columns[13]: 'energia_total',
    df_raw.columns[14]: 'punto_max_ace_C',
    df_raw.columns[15]: 'pendiente_ace_Ch',
    df_raw.columns[16]: 'punto_max_ppal_C',
    df_raw.columns[17]: 'pendiente_ppal_Ch',
    df_raw.columns[18]: 'energia_temp_Jg',
}

tiempos_pen   = [3,6,10,15,20,30,45,60,75,90,105,120,135,150,165,180,195,210,225,240]
tiempos_clavo = [4,6,8,10,12,20,24]
tiempos_comp  = [1, 1.25, 3, 7, 28]

for i, t in enumerate(tiempos_pen):
    rename_map[df_raw.columns[19 + i]] = f'pen_{t}min'
for i, t in enumerate(tiempos_clavo):
    rename_map[df_raw.columns[39 + i]] = f'clavo_{t}h'
for i, t in enumerate(tiempos_comp):
    rename_map[df_raw.columns[46 + i]] = f'comp_{t}d'

df = df_raw.rename(columns=rename_map).dropna(how='all')

# ── 3. Definición de columnas ────────────────────────────────────────────────
COL_CALOR = ['punto_max_ace_mWg', 'pendiente_ace_mWgh', 'energia_ace_Jg',
             'punto_max_ppal_mWg', 'pendiente_ppal_mWgh', 'energia_ppal_Jg',
             'energia_total']
COL_META  = ['material', 'relacion_ac', 'cemento', 'tipo_acelerante',
             'acelerante', 'dosificacion']

SERIES_PEN   = [f'pen_{t}min' for t in tiempos_pen]
SERIES_CLAVO = [f'clavo_{t}h' for t in tiempos_clavo]
SERIES_COMP  = [f'comp_{t}d'  for t in tiempos_comp]

# ── 4. Limpieza de tipos ─────────────────────────────────────────────────────
df['energia_total'] = (df['energia_total'].astype(str)
    .str.replace('\xa0', '', regex=False)
    .str.replace(',', '.', regex=False)
    .str.replace('>', '', regex=False)
    .replace(['-', 'nan', 'None', ''], np.nan))
df['energia_total'] = pd.to_numeric(df['energia_total'], errors='coerce')

cols_num = (['relacion_ac', 'dosificacion'] + COL_CALOR[:-1] +
            SERIES_PEN + SERIES_CLAVO + SERIES_COMP)
for col in cols_num:
    if col in df.columns:
        df[col] = (df[col].astype(str)
                   .str.replace('>', '', regex=False)
                   .replace(['-', 'nan', 'None', ''], np.nan))
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Texto → etiqueta numérica. NaN se mantiene como -1 (no como categoría "nan").
factorizacion = {}
for col in ['material', 'cemento', 'tipo_acelerante', 'acelerante']:
    s = df[col].astype(str).str.strip().replace({'nan': np.nan, 'None': np.nan, '': np.nan})
    codigos, valores_unicos = pd.factorize(s)   # NaN -> -1 automáticamente
    df[col] = codigos
    factorizacion[col] = valores_unicos

# ── 5. Features ──────────────────────────────────────────────────────────────
features_ok = [
    'material', 'relacion_ac', 'cemento', 'tipo_acelerante',
    'acelerante', 'dosificacion',
    'punto_max_ace_mWg', 'pendiente_ace_mWgh', 'energia_ace_Jg',
    'punto_max_ppal_mWg', 'pendiente_ppal_mWgh', 'energia_ppal_Jg',
    'energia_total',
]
features_ok = [f for f in features_ok if f in df.columns]

vacias = [f for f in features_ok if df[f].notna().sum() < 1]
if vacias:
    print(f"⚠️ Descartadas por estar (casi) vacías: {vacias}")
features_ok = [f for f in features_ok if f not in vacias]

COLS_CATEGORICAS = [c for c in ['material', 'cemento', 'tipo_acelerante', 'acelerante']
                    if c in features_ok]
COLS_NUM_KNN = [c for c in features_ok if c not in COLS_CATEGORICAS]

# X cruda (conserva NaN) e y
X = df[features_ok].copy()
y = df[SERIES_COMP].copy()

# ── 5b. Imputación KNN (lo que faltaba) ──────────────────────────────────────
# Se escala TODO solo para calcular la distancia KNN (si no, las columnas de mayor
# magnitud dominan). Tras imputar se vuelve a unidades reales y se restauran las
# categóricas a su entero original. Se dejan AJUSTADOS `scaler` e `imputer`.
scaler  = StandardScaler()
imputer = KNNImputer(n_neighbors=5, weights='distance')

X_scaled     = scaler.fit_transform(X)            # StandardScaler ignora NaN en fit
X_imp_scaled = imputer.fit_transform(X_scaled)    # imputa en espacio escalado
X_imp_vals   = scaler.inverse_transform(X_imp_scaled)

X_imp = pd.DataFrame(X_imp_vals, columns=features_ok, index=X.index)
X_imp[COLS_CATEGORICAS] = X[COLS_CATEGORICAS].values  # categóricas sin tocar

# ── 6. Auditoría final ───────────────────────────────────────────────────────
print("=== AUDITORÍA FINAL ===")
print(f"Total muestras: {len(df)}")
print(f"features_ok ({len(features_ok)}): {features_ok}")
print(f"NaN restantes en X_imp: {int(X_imp.isna().sum().sum())}")
print("\nTargets de compresión disponibles:")
for col in y.columns:
    print(f"  {col}: {y[col].notna().sum()} muestras válidas de {len(y)}")
print(f"\nObjetos listos para Celda 2: df, features_ok, X (cruda), X_imp (imputada), "
      f"y, imputer, scaler, factorizacion")

# ── 7. Equivalencias de los valores factorizados ─────────────────────────────
print("\n=== EQUIVALENCIAS DE VARIABLES FACTORIZADAS ===")
for col in ['material', 'cemento', 'tipo_acelerante', 'acelerante']:
    print(f"\n  {col} ({len(factorizacion[col])} categorías):")
    for codigo, texto in enumerate(factorizacion[col]):
        print(f"    {codigo:>3} → {texto}")

# Versión en tabla única, ordenada por columna y luego por código
print("\n=== TABLA CONSOLIDADA (ordenada) ===")
filas_tabla = []
for col in ['material', 'cemento', 'tipo_acelerante', 'acelerante']:
    for codigo, texto in enumerate(factorizacion[col]):
        filas_tabla.append({'variable': col, 'codigo': codigo, 'valor_original': texto})

tabla_factorizacion = pd.DataFrame(filas_tabla).sort_values(
    ['variable', 'codigo']).reset_index(drop=True)
print(tabla_factorizacion.to_string(index=False))

# ──────────────────────────────────────────────────────────────────────────────
# SISTEMA DE FIGURAS PARA LATEX (estilo y tamaño coherentes en TODO el cuaderno)
# ──────────────────────────────────────────────────────────────────────────────
# Reglas:
#   · Una figura = un gráfico (un PDF por gráfico). Sin títulos superiores.
#   · El tamaño depende del TIPO de gráfico, definido por su par de ejes:
#       dos gráficos con los MISMOS dos ejes son del mismo tipo (mismo tamaño);
#       si algún eje difiere, es otro tipo (puede tener otro tamaño).
#   · Ancho máximo = 20% menor que el ancho "lleno" de Colab (~20 in) → 16 in.
#   · Altura mínima > 20 cm (≈ 8 in).
#   · Estilo visual común (fuentes, rejilla, leyenda, grosor) vía rcParams.
import matplotlib
import matplotlib.pyplot as plt

COLAB_W_FULL = 20.0                 # ancho de referencia "a pantalla completa"
MAX_W        = 0.8 * COLAB_W_FULL   # tope de ancho = 16 in (20% menos)
MIN_H        = 8.0                  # altura mínima ≈ 20 cm

# Tamaño por TIPO de gráfico (ancho ≤ MAX_W, alto ≥ MIN_H):
AX_CURVA   = (MAX_W, MIN_H)         # x=Tiempo(log) · y=Resistencia → banner ancho 2:1
AX_SCATTER = (MIN_H, MIN_H)         # x=Real · y=Predicho           → cuadrado 8×8
AX_IMPORT  = (11.0,  MIN_H)         # x=Importancia · y=variable     → barras horizontales
AX_BAR     = (MAX_W, MIN_H)         # x=Tiempo(cat) · y=R²/MAE       → barras

# Texto grande y coherente en todas las figuras
FS_LABEL, FS_TICK, FS_LEG = 18, 15, 14
plt.rcParams.update({
    'figure.dpi': 110, 'savefig.dpi': 110,
    'font.size': FS_TICK,
    'axes.labelsize': FS_LABEL, 'axes.titlesize': FS_LABEL,
    'xtick.labelsize': FS_TICK, 'ytick.labelsize': FS_TICK,
    'legend.fontsize': FS_LEG, 'legend.framealpha': 0.9,
    'grid.linestyle': '--', 'grid.alpha': 0.3, 'axes.axisbelow': True,
    'lines.linewidth': 2.5,
})

def figsize(ax_wh, ncols=1, nrows=1):
    """Tamaño de figura (cada gráfico es de un solo eje → ncols=nrows=1)."""
    return (ax_wh[0] * ncols, ax_wh[1] * nrows)

# Registro global de PDFs → se empaquetan en un ZIP único en la Celda 4
FIGURAS_PDF = []
def guardar_pdf(fig, path):
    """Guarda en PDF vectorial al tamaño EXACTO del tipo (sin recortar, para que
    todas las figuras de un mismo tipo midan igual y se respeten ancho/alto) y la
    registra para el ZIP final. tight_layout encaja las etiquetas dentro del lienzo."""
    try:
        fig.tight_layout()
    except Exception:
        pass
    fig.savefig(path)            # sin bbox_inches='tight' → tamaño = figsize del tipo
    if path not in FIGURAS_PDF:
        FIGURAS_PDF.append(path)
    return path

# ==============================================================================
# CELDA 2 — MODELOS BASE (RF + XGBoost) + OPTIMIZACIÓN RÁPIDA
# ==============================================================================
# - Entrena un modelo por punto temporal para RF y XGBoost
# - Optimiza con RandomizedSearchCV por grupo (mucho más rápido que el AG)
# - 4 paneles comparativos + curva PCHIP suavizada + panel MAE
# - Tablas de R² y MAE impresas en consola
# Requiere haber ejecutado la Celda 1.
# ==============================================================================
!pip install xgboost -q   # descomenta si no está instalado

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy.interpolate import PchipInterpolator
from scipy.stats import randint, uniform
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import ShuffleSplit, cross_val_score, RandomizedSearchCV
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.impute import SimpleImputer
from collections import defaultdict
import warnings
warnings.filterwarnings("ignore")

# ── Serie temporal unificada (horas) ─────────────────────────────────────────
TIEMPOS_PEN   = [3,6,10,15,20,30,45,60,75,90,105,120,135,150,165,180,195,210,225,240]
TIEMPOS_CLAVO = [4, 6, 8, 10, 12, 20, 24]
TIEMPOS_COMP  = [1, 1.25, 3, 7, 28]

SERIE_COMPLETA = (
    [(t / 60,   f'pen_{t}min',  'Penetración', '#3B82F6') for t in TIEMPOS_PEN]   +
    [(float(t), f'clavo_{t}h', 'Clavo',        '#10B981') for t in TIEMPOS_CLAVO] +
    [(t * 24,   f'comp_{t}d',  'Compresión',   '#EF4444') for t in TIEMPOS_COMP]
)

def etiqueta_tiempo(horas):
    if horas < 1:    return f"{int(round(horas * 60))} min"
    elif horas < 24: return f"{horas:.4g} h"
    else:            return f"{horas/24:.4g} d"

# ── Features e imputación KNN (escalada) ─────────────────────────────────────
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

FEATURES_CANDIDATOS = [
    'material', 'relacion_ac', 'cemento', 'tipo_acelerante',
    'acelerante', 'dosificacion',
    'punto_max_ace_mWg', 'pendiente_ace_mWgh', 'energia_ace_Jg',
    'punto_max_ppal_mWg', 'pendiente_ppal_mWgh', 'energia_ppal_Jg',
    'energia_total',
]
features_ok = [f for f in FEATURES_CANDIDATOS if f in df.columns]

# KNN usa distancias, así que las columnas numéricas se escalan para que ninguna
# domine por su rango. Las categóricas factorizadas NO se escalan.
COLS_CATEGORICAS = ['material', 'cemento', 'tipo_acelerante', 'acelerante']
COLS_NUM_KNN = [c for c in features_ok if c not in COLS_CATEGORICAS]
scaler_knn = StandardScaler()
df_scaled = df[features_ok].copy()
df_scaled[COLS_NUM_KNN] = scaler_knn.fit_transform(df[COLS_NUM_KNN])

imputer = KNNImputer(n_neighbors=5)
X_scaled_imp = imputer.fit_transform(df_scaled)

# Desescalar las numéricas para volver a unidades originales
import pandas as pd
X_imp_df = pd.DataFrame(X_scaled_imp, columns=features_ok, index=df.index)
X_imp_df[COLS_NUM_KNN] = scaler_knn.inverse_transform(X_imp_df[COLS_NUM_KNN])
X_imp = X_imp_df.values

print(f"Features usados ({len(features_ok)}): {features_ok}")
print(f"Imputación: KNN (5 vecinos, escalado). NaN restantes: {np.isnan(X_imp).sum()}")

# ══════════════════════════════════════════════════════════════════════════════
# 1. PARÁMETROS BASE (sin optimización)
# ══════════════════════════════════════════════════════════════════════════════
PARAMS_RF  = dict(n_estimators=300, max_depth=8, min_samples_leaf=3)
PARAMS_XGB = dict(n_estimators=200, max_depth=3, learning_rate=0.05,
                  subsample=0.8, colsample_bytree=0.7, min_child_weight=3,
                  reg_lambda=10.0, reg_alpha=1.0)

# Diccionarios de params por serie (por compatibilidad con predecir_curva_completa_xgb)
params_xgb_grupo = {s: PARAMS_XGB for s in ['Penetración', 'Clavo', 'Compresión']}
params_rf_grupo  = {s: PARAMS_RF  for s in ['Penetración', 'Clavo', 'Compresión']}


from sklearn.model_selection import train_test_split

# ══════════════════════════════════════════════════════════════════════════════
# 2. ENTRENAR CADA PUNTO TEMPORAL (con holdout real 80/20)
# ══════════════════════════════════════════════════════════════════════════════
resultados_rf, resultados_xgb = {}, {}
ss = ShuffleSplit(n_splits=20, test_size=0.25, random_state=42)

N_MIN_HOLDOUT = 15  # con menos, el 20% son <3 muestras: no es fiable

for horas, col, serie, color in SERIE_COMPLETA:
    if col not in df.columns:
        continue
    mask = df[col].notna()
    n    = mask.sum()
    if n < 12:
        continue
    y_col = df.loc[mask, col].values.astype(float)
    X_col = X_imp[mask.values]

    # Split fijo 80/20: el modelo de holdout NUNCA ve estas muestras al ajustar
    hacer_holdout = n >= N_MIN_HOLDOUT
    if hacer_holdout:
        X_tr, X_te, y_tr, y_te = train_test_split(
            X_col, y_col, test_size=0.2, random_state=42
        )
    else:
        X_tr, y_tr = X_col, y_col
        X_te, y_te = None, None

    for res, ctor in [
        (resultados_rf,  lambda: RandomForestRegressor(**PARAMS_RF, random_state=42, n_jobs=-1)),
        (resultados_xgb, lambda: XGBRegressor(**PARAMS_XGB, random_state=42, verbosity=0)),
    ]:
        # (a) CV repetida sobre el conjunto de entrenamiento (no toca el holdout)
        r2_cv = cross_val_score(ctor(), X_tr, y_tr, cv=ss, scoring='r2')

        # (b) Evaluación honesta sobre el 20% nunca visto durante el ajuste
        if hacer_holdout:
            modelo_ho = ctor().fit(X_tr, y_tr)
            yp_te = modelo_ho.predict(X_te)
            r2_holdout  = r2_score(y_te, yp_te)
            mae_holdout = mean_absolute_error(y_te, yp_te)
        else:
            r2_holdout, mae_holdout = None, None

        # (c) Modelo final de producción: ajustado con TODOS los datos
        #     (es el que alimenta curvas, importancias, y se exporta a la app)
        modelo = ctor().fit(X_col, y_col)
        yp = modelo.predict(X_col)

        res[col] = {
            'horas': horas, 'serie': serie, 'color': color, 'n': n,
            'n_train': len(X_tr), 'n_test': (len(X_te) if hacer_holdout else 0),
            'y_real': y_col, 'y_pred': yp, 'X_col': X_col,
            'r2_train': r2_score(y_col, yp), 'r2_cv': r2_cv.mean(),
            'r2_cv_std': r2_cv.std(), 'mae': mean_absolute_error(y_col, yp),
            'r2_holdout': r2_holdout, 'mae_holdout': mae_holdout,
            'modelo': modelo, 'importancias': modelo.feature_importances_,
        }

orden = sorted(resultados_rf.keys(), key=lambda k: resultados_rf[k]['horas'])
print(f"✅ {len(orden)} puntos temporales entrenados (RF y XGB)")


# ══════════════════════════════════════════════════════════════════════════════
# 3. TABLAS DE RESULTADOS (R² y MAE en consola, incluye holdout real)
# ══════════════════════════════════════════════════════════════════════════════
def _fmt(v, fmt='{:.3f}'):
    return fmt.format(v) if v is not None else '  N/A '

print("\n" + "="*112)
print(f"  {'Tiempo':>10} {'Serie':<13} {'n':>4} {'n_te':>5} | "
      f"{'RF R²cv':>8} {'RF MAE':>7} | {'RF R²ho':>8} {'RF MAEho':>9} | "
      f"{'XGB R²cv':>9} {'XGB MAE':>8} | {'XGB R²ho':>9} {'XGB MAEho':>10}")
print("="*112)
for k in orden:
    r, x = resultados_rf[k], resultados_xgb[k]
    print(f"  {etiqueta_tiempo(r['horas']):>10} {r['serie']:<13} {r['n']:>4} {r['n_test']:>5} | "
          f"{r['r2_cv']:>8.3f} {r['mae']:>7.2f} | "
          f"{_fmt(r['r2_holdout']):>8} {_fmt(r['mae_holdout'],'{:.2f}'):>9} | "
          f"{x['r2_cv']:>9.3f} {x['mae']:>8.2f} | "
          f"{_fmt(x['r2_holdout']):>9} {_fmt(x['mae_holdout'],'{:.2f}'):>10}")
print("="*112)
print("  R²ho/MAEho = evaluación sobre el 20% de datos NUNCA visto durante el ajuste")
print(f"  (N/A cuando n < {N_MIN_HOLDOUT}: un holdout de 2-3 muestras no es estadísticamente fiable)")
print("="*112)

# Promedios
rf_r2   = np.mean([resultados_rf[k]['r2_cv']  for k in orden])
xgb_r2  = np.mean([resultados_xgb[k]['r2_cv'] for k in orden])
rf_mae  = np.mean([resultados_rf[k]['mae']  for k in orden])
xgb_mae = np.mean([resultados_xgb[k]['mae'] for k in orden])

ks_ho      = [k for k in orden if resultados_rf[k]['r2_holdout'] is not None]
rf_r2_ho   = np.mean([resultados_rf[k]['r2_holdout']   for k in ks_ho]) if ks_ho else None
xgb_r2_ho  = np.mean([resultados_xgb[k]['r2_holdout']  for k in ks_ho]) if ks_ho else None
rf_mae_ho  = np.mean([resultados_rf[k]['mae_holdout']  for k in ks_ho]) if ks_ho else None
xgb_mae_ho = np.mean([resultados_xgb[k]['mae_holdout'] for k in ks_ho]) if ks_ho else None

print(f"  {'PROMEDIO':>10} {'':<13} {'':>4} {'':>5} | "
      f"{rf_r2:>8.3f} {rf_mae:>7.2f} | {_fmt(rf_r2_ho):>8} {_fmt(rf_mae_ho,'{:.2f}'):>9} | "
      f"{xgb_r2:>9.3f} {xgb_mae:>8.2f} | {_fmt(xgb_r2_ho):>9} {_fmt(xgb_mae_ho,'{:.2f}'):>10}")
print("="*112)
print(f"  (promedio R²holdout sobre {len(ks_ho)}/{len(orden)} puntos con n ≥ {N_MIN_HOLDOUT})")


# ══════════════════════════════════════════════════════════════════════════════
# 4. VISUALIZACIÓN — CADA PANEL EN SU PROPIA FIGURA (PDF vectorial para LaTeX)
# ══════════════════════════════════════════════════════════════════════════════
horas_arr = np.array([resultados_rf[k]['horas'] for k in orden])

def _buscar_col(target_horas):
    return min(orden, key=lambda k: abs(resultados_rf[k]['horas'] - target_horas))

def graficar_modelo(res, nombre_modelo, color_main, color_series):
    """Genera 5 figuras independientes (una por panel) y las guarda en PDF."""
    c_pen, c_cla, c_com = color_series
    slug = nombre_modelo.lower().replace(" ", "_")
    series_cfg = [('Penetración', c_pen), ('Clavo', c_cla), ('Compresión', c_com)]
    x = np.arange(len(orden))

    # ── FIGURA A: curva temporal + banda ±1σ + n por nodo ──
    fig, ax = plt.subplots(figsize=figsize(AX_CURVA))
    for serie, col_s in series_cfg:
        ks   = [k for k in orden if res[k]['serie'] == serie]
        h_s  = np.array([res[k]['horas'] for k in ks])
        mp_s = np.array([res[k]['y_pred'].mean() for k in ks])
        sd_s = np.array([res[k]['y_pred'].std() for k in ks])
        mr_s = np.array([res[k]['y_real'].mean() for k in ks])
        ns   = [res[k]['n'] for k in ks]
        ax.fill_between(h_s, mp_s - sd_s, mp_s + sd_s, alpha=0.12, color=col_s)
        ax.plot(h_s, mp_s, 'o-', color=col_s, lw=2.2, ms=6, label=f'{serie} predicho')
        ax.plot(h_s, mr_s, 's--', color=col_s, lw=1.5, ms=5, alpha=0.6,
                label=f'{serie} real')
        for h, r, n in zip(h_s, mr_s, ns):
            ax.annotate(f'n={n}', (h, r), textcoords='offset points',
                        xytext=(0, 8), ha='center', fontsize=7, color='#374151')
    ax.set_xscale('log')
    ax.set_xticks(horas_arr)
    ax.set_xticklabels([etiqueta_tiempo(h) for h in horas_arr],
                       rotation=55, ha='right', fontsize=FS_TICK)
    ax.set_xlabel('Tiempo (horas) — escala log', fontsize=FS_LABEL)
    ax.set_ylabel('Resistencia (MPa)', fontsize=FS_LABEL)
    ax.tick_params(axis='y', labelsize=FS_TICK)
    ax.legend(fontsize=FS_LEG, ncol=3); ax.grid(True, alpha=0.25, which='both')
    guardar_pdf(fig, f'curva_temporal_{slug}.pdf')
    plt.show()

    # ── FIGURA B: R² train vs CV ──
    fig, ax_b = plt.subplots(figsize=figsize(AX_BAR))
    r2_tr = [res[k]['r2_train'] for k in orden]
    r2_cv = [res[k]['r2_cv'] for k in orden]
    ax_b.bar(x - 0.2, r2_tr, 0.35, label='R² Train',
             color=color_main, alpha=0.9, edgecolor='white', lw=0.5)
    ax_b.bar(x + 0.2, r2_cv, 0.35, label='R² CV (20×)',
             color=color_main, alpha=0.4, edgecolor='white', lw=0.5,
             yerr=[res[k]['r2_cv_std'] for k in orden], capsize=2,
             ecolor='#374151', error_kw={'lw': 0.8})
    ax_b.axhline(0, color='black', lw=0.8, ls='--')
    ax_b.axhline(0.5, color='green', lw=0.8, ls=':', alpha=0.6, label='R²=0.5')
    ax_b.set_xticks(x)
    ax_b.set_xticklabels([etiqueta_tiempo(res[k]['horas']) for k in orden],
                         rotation=50, ha='right', fontsize=FS_TICK)
    ax_b.set_ylabel('R²', fontsize=FS_LABEL)
    ax_b.tick_params(axis='y', labelsize=FS_TICK)
    ax_b.legend(fontsize=FS_LEG); ax_b.grid(True, alpha=0.25, axis='y'); ax_b.set_ylim(-1.3, 1.05)
    guardar_pdf(fig, f'r2_cv_{slug}.pdf')
    plt.show()

    # ── FIGURA C: importancia de variables ──
    fig, ax_c = plt.subplots(figsize=figsize(AX_IMPORT))
    target_ref = max(orden, key=lambda k: res[k]['n'])
    imp        = res[target_ref]['importancias']
    orden_imp  = np.argsort(imp)
    names_ord  = [features_ok[i] for i in orden_imp]
    vals_ord   = imp[orden_imp]
    pal = plt.cm.viridis(np.linspace(0.2, 0.9, len(names_ord)))
    ax_c.barh(names_ord, vals_ord, color=pal, edgecolor='white', lw=0.5)
    for i, v in enumerate(vals_ord):
        ax_c.text(v + vals_ord.max()*0.01, i, f'{v:.3f}', va='center', fontsize=9)
    ax_c.set_xlabel('Importancia', fontsize=FS_LABEL)
    ax_c.set_xlim(0, vals_ord.max() * 1.25)
    ax_c.grid(True, alpha=0.25, axis='x'); ax_c.tick_params(labelsize=FS_TICK)
    guardar_pdf(fig, f'importancia_{slug}.pdf')
    plt.show()

    # ── FIGURA MAE ──
    fig, ax_mae = plt.subplots(figsize=figsize(AX_BAR))
    ax_mae.bar(x, [res[k]['mae'] for k in orden], 0.6,
               color=[res[k]['color'] for k in orden], alpha=0.85,
               edgecolor='white', lw=0.5)
    ax_mae.set_xticks(x)
    ax_mae.set_xticklabels([etiqueta_tiempo(res[k]['horas']) for k in orden],
                           rotation=50, ha='right', fontsize=FS_TICK)
    ax_mae.set_ylabel('MAE (MPa)', fontsize=FS_LABEL)
    ax_mae.tick_params(axis='y', labelsize=FS_TICK)
    ax_mae.grid(True, alpha=0.25, axis='y')
    guardar_pdf(fig, f'mae_{slug}.pdf')
    plt.show()

    # ── FIGURA scatter por edad (un PDF individual por edad) ──
    target_pob = max(orden, key=lambda k: res[k]['n'])
    edades = [
        (_buscar_col(0.5),  '30 min',                                          '30min'),
        (_buscar_col(24.0), '1 día',                                           '1dia'),
        (target_pob, etiqueta_tiempo(res[target_pob]['horas']) + ' (+datos)',  'poblada'),
    ]
    for k, etiq, eslug in edades:
        r = res[k]
        fig, ax_s = plt.subplots(figsize=figsize(AX_SCATTER))
        ax_s.scatter(r['y_real'], r['y_pred'], color=color_main, alpha=0.6, s=45,
                     edgecolors='white', lw=0.4,
                     label=f'{etiq}\nR²t={r["r2_train"]:.2f}  MAE={r["mae"]:.2f}  n={r["n"]}')
        lim = [min(r['y_real'].min(), r['y_pred'].min())*0.9,
               max(r['y_real'].max(), r['y_pred'].max())*1.08]
        ax_s.plot(lim, lim, 'k--', lw=1.2, label='Ideal (y=x)')
        ax_s.set_xlim(lim); ax_s.set_ylim(lim)
        ax_s.set_xlabel('Real (MPa)', fontsize=FS_LABEL)
        ax_s.set_ylabel('Predicho (MPa)', fontsize=FS_LABEL)
        ax_s.legend(fontsize=FS_LEG, loc='upper left', framealpha=0.9)
        ax_s.grid(True, alpha=0.25); ax_s.tick_params(labelsize=FS_TICK)
        guardar_pdf(fig, f'scatter_{slug}_{eslug}.pdf')
        plt.show()

# Generar las figuras de cada modelo
graficar_modelo(resultados_rf,  'Random Forest',
                '#2563EB', ('#3B82F6', '#10B981', '#EF4444'))
graficar_modelo(resultados_xgb, 'XGBoost',
                '#DC2626', ('#1E40AF', '#047857', '#991B1B'))


# ══════════════════════════════════════════════════════════════════════════════
# 5. CURVA SUAVIZADA CON PCHIP (ancho completo)
# ══════════════════════════════════════════════════════════════════════════════
def _deduplicar(h, r):
    acum = defaultdict(list)
    for hi, ri in zip(h, r):
        acum[hi].append(ri)
    hu = np.array(sorted(acum.keys()))
    return hu, np.array([np.mean(acum[k]) for k in hu])

plt.close('all')
fig, ax = plt.subplots(figsize=figsize(AX_CURVA))   # banner ancho, como las demás curvas
for res, nombre, color in [(resultados_rf, 'Random Forest', '#2563EB'),
                            (resultados_xgb, 'XGBoost', '#DC2626')]:
    h_raw = np.array([res[k]['horas'] for k in orden])
    r_raw = np.array([res[k]['y_pred'].mean() for k in orden])
    hu, ru = _deduplicar(h_raw, r_raw)
    interp = PchipInterpolator(hu, ru)
    h_fino = np.logspace(np.log10(hu.min()), np.log10(hu.max()), 300)
    ax.plot(h_fino, np.clip(interp(h_fino), 0, None), '-', color=color, lw=2.5,
            label=f'{nombre} (PCHIP)')
    ax.scatter(h_raw, r_raw, color=color, s=35, zorder=5, edgecolors='white', lw=0.5)
h_real = np.array([resultados_rf[k]['horas'] for k in orden])
r_real = np.array([resultados_rf[k]['y_real'].mean() for k in orden])
ax.scatter(h_real, r_real, color='black', marker='x', s=60, zorder=6, label='Media real lab')
ax.set_xscale('log')
ax.set_xticks(horas_arr)
ax.set_xticklabels([etiqueta_tiempo(h) for h in horas_arr], rotation=55, ha='right', fontsize=FS_TICK)
ax.set_xlabel('Tiempo (horas) — escala log', fontsize=FS_LABEL)
ax.set_ylabel('Resistencia (MPa)', fontsize=FS_LABEL)
ax.tick_params(axis='y', labelsize=FS_TICK)
ax.legend(fontsize=FS_LEG); ax.grid(True, which='both', ls='--', alpha=0.3)
plt.tight_layout()
guardar_pdf(fig, 'curva_pchip_suave.pdf')
plt.show()


# ══════════════════════════════════════════════════════════════════════════════
# 6. DESCARGA DE LOS MODELOS PARA APLICACION WEB
# ══════════════════════════════════════════════════════════════════════════════
import joblib
from google.colab import files

# Calcular las combinaciones válidas familia → productos desde el dataframe
# (antes de factorizar necesitamos el texto, así que lo reconstruimos del df original)
# Como en la Celda 1 ya factorizamos, usamos factorizacion para mapear de vuelta
combos_validos = {}
for cod_tipo in df['tipo_acelerante'].dropna().unique():
    # productos (códigos) que aparecen con esta familia
    mask = df['tipo_acelerante'] == cod_tipo
    productos_cod = sorted(df.loc[mask, 'acelerante'].dropna().unique().tolist())
    nombre_tipo = factorizacion['tipo_acelerante'][int(cod_tipo)]
    combos_validos[nombre_tipo] = productos_cod

# Diccionario de factorización en formato portable
factor_portable = {k: list(v) for k, v in factorizacion.items()}

# Imputador de respaldo para la app (mediana). El KNN se usó solo para limpiar
# el dataset de entrenamiento; en la app el usuario da datos completos, así que
# un fallback de mediana es suficiente y portable.
from sklearn.impute import SimpleImputer
imputer_app = SimpleImputer(strategy='median').fit(df[features_ok])

def construir_paquete(resultados, tipo_modelo):
    return {
        'resultados': {k: {'modelo': v['modelo'], 'horas': v['horas'],
                           'serie': v['serie']} for k, v in resultados.items()},
        'imputer': imputer_app,          # ← mediana como fallback (portable)
        'features_ok': features_ok,
        'orden': orden,
        'factorizacion': factor_portable,
        'combos_validos': combos_validos,
        'tipo': tipo_modelo,
    }

joblib.dump(construir_paquete(resultados_rf,  'Random Forest'), 'modelo_hormigon_rf.pkl')
joblib.dump(construir_paquete(resultados_xgb, 'XGBoost'),       'modelo_hormigon_xgb.pkl')

print("✅ Modelos guardados con factorización y combinaciones válidas")

# ==============================================================================
# CELDA 2.B — MODELO ÚNICO CON TIEMPO COMO VARIABLE
# Figuras separadas, A4 horizontal, sin títulos, fuentes legibles, PDF para LaTeX
# ==============================================================================
!pip install xgboost -q

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import PchipInterpolator
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.metrics import r2_score, mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# Tamaños y fuentes: se heredan del sistema unificado definido en la Celda 1
# (AX_CURVA, AX_SCATTER, AX_IMPORT, FS_*, figsize(), guardar_pdf()).

# ── Serie temporal ───────────────────────────────────────────────────────────
TIEMPOS_PEN   = [3,6,10,15,20,30,45,60,75,90,105,120,135,150,165,180,195,210,225,240]
TIEMPOS_CLAVO = [4, 6, 8, 10, 12, 20, 24]
TIEMPOS_COMP  = [1, 1.25, 3, 7, 28]

SERIE = (
    [(t / 60,   f'pen_{t}min',  'Penetración') for t in TIEMPOS_PEN]   +
    [(float(t), f'clavo_{t}h',  'Clavo')       for t in TIEMPOS_CLAVO] +
    [(t * 24,   f'comp_{t}d',   'Compresión')  for t in TIEMPOS_COMP]
)
COLORES = {'Penetración':'#3B82F6', 'Clavo':'#10B981', 'Compresión':'#EF4444'}

# ── Construir dataset aplanado ───────────────────────────────────────────────
X_imp = imputer.transform(df[features_ok])

X_plano, y_plano, serie_plano = [], [], []
for horas, col, serie in SERIE:
    if col not in df.columns:
        continue
    mask = df[col].notna()
    if mask.sum() < 5:
        continue
    X_sub = X_imp[mask.values]
    y_sub = df.loc[mask, col].values.astype(float)
    X_plano.append(np.hstack((X_sub, np.full((len(y_sub), 1), horas))))
    y_plano.append(y_sub)
    serie_plano += [serie] * len(y_sub)

X_final = np.vstack(X_plano)
y_final = np.concatenate(y_plano)
serie_plano = np.array(serie_plano)
nombres_variables = features_ok + ['tiempo_horas']
print(f"Dataset aplanado: {X_final.shape[0]} muestras × {X_final.shape[1]} variables")

# ── SEPARAR 20% DE TEST (OJO: split por filas → ver nota sobre fuga) ─────────
X_tr, X_te, y_tr, y_te, s_tr, s_te = train_test_split(
    X_final, y_final, serie_plano, test_size=0.2, random_state=42)
print(f"Entrenamiento: {len(X_tr)} | Test: {len(X_te)}")

# ══════════════════════════════════════════════════════════════════════════════
# 1. ENTRENAR Y EVALUAR
# ══════════════════════════════════════════════════════════════════════════════
modelo_rf = RandomForestRegressor(n_estimators=400, max_depth=10,
                                  min_samples_leaf=3, random_state=42, n_jobs=-1)
modelo_xgb = XGBRegressor(n_estimators=300, max_depth=4, learning_rate=0.05,
                          subsample=0.8, colsample_bytree=0.8, min_child_weight=3,
                          reg_lambda=10.0, reg_alpha=1.0, random_state=42, verbosity=0)

metricas = {}
print("\n" + "="*72)
print(f"  {'Modelo':<20} {'R² train':>9} {'R² TEST':>9} {'MAE test':>10} {'R² CV':>8}")
print("="*72)
cv = KFold(n_splits=5, shuffle=True, random_state=42)
for nombre, m in [('Random Forest', modelo_rf), ('XGBoost', modelo_xgb)]:
    m.fit(X_tr, y_tr)
    r2_tr  = r2_score(y_tr, m.predict(X_tr))
    r2_te  = r2_score(y_te, m.predict(X_te))
    mae_te = mean_absolute_error(y_te, m.predict(X_te))
    r2_cv  = cross_val_score(m, X_final, y_final, cv=cv, scoring='r2').mean()
    metricas[nombre] = dict(r2_train=r2_tr, r2_test=r2_te, mae_test=mae_te, r2_cv=r2_cv)
    print(f"  {nombre:<20} {r2_tr:>9.3f} {r2_te:>9.3f} {mae_te:>9.2f}  {r2_cv:>8.3f}")
print("="*72)

# ── Datos para las curvas ────────────────────────────────────────────────────
medianas  = np.median(X_final[:, :-1], axis=0)
horas_eje = np.logspace(np.log10(3/60), np.log10(672), 300)
X_curva   = np.column_stack([np.tile(medianas, (len(horas_eje), 1)), horas_eje])

def suavizar(pred, horas, n_puntos=25):
    idx_sub = np.linspace(0, len(horas)-1, n_puntos, dtype=int)
    h_sub = horas[idx_sub]; p_sub = np.maximum.accumulate(pred[idx_sub])
    return np.clip(PchipInterpolator(h_sub, p_sub)(horas), 0, None)

horas_real, R_media, R_std, col_serie = [], [], [], []
for horas, col, serie in SERIE:
    if col not in df.columns: continue
    vals = df[col].dropna()
    if len(vals) < 5: continue
    horas_real.append(horas); R_media.append(vals.mean())
    R_std.append(vals.std()); col_serie.append(serie)
horas_real = np.array(horas_real); R_media = np.array(R_media)
R_std = np.array(R_std); col_serie = np.array(col_serie)

pred_rf_crudo  = modelo_rf.predict(X_curva)
pred_xgb_crudo = modelo_xgb.predict(X_curva)

XTICKS = [3/60, 1, 4, 24, 72, 168, 672]
XLABS  = ['3 min','1 h','4 h','1 d','3 d','7 d','28 d']

def dibujar_curva(pred_rf, pred_xgb, etiqueta, fname):
    fig, ax = plt.subplots(figsize=figsize(AX_CURVA))
    ax.plot(horas_eje, pred_rf, '-', color='#2563EB', lw=2.8,
            label=f'Random Forest ({etiqueta})')
    ax.plot(horas_eje, pred_xgb, '-', color='#DC2626', lw=2.8,
            label=f'XGBoost ({etiqueta})')
    for serie, c in COLORES.items():
        m = col_serie == serie
        ax.errorbar(horas_real[m], R_media[m], yerr=R_std[m], fmt='o', color=c,
                    ms=8, capsize=4, capthick=1.3, markeredgecolor='white',
                    markeredgewidth=0.9, zorder=6, label=f'Lab {serie}')
    ax.set_xscale('log'); ax.set_xticks(XTICKS); ax.set_xticklabels(XLABS)
    ax.set_xlabel('Tiempo (escala log)', fontsize=FS_LABEL)
    ax.set_ylabel('Resistencia (MPa)', fontsize=FS_LABEL)
    ax.tick_params(axis='both', labelsize=FS_TICK)
    ax.legend(fontsize=FS_LEG, ncol=2, framealpha=0.9)
    ax.grid(True, which='both', ls='--', alpha=0.3)
    plt.tight_layout()
    guardar_pdf(fig, fname)
    plt.show()

# ── FIGURA 1: curva cruda ────────────────────────────────────────────────────
dibujar_curva(pred_rf_crudo, pred_xgb_crudo, 'crudo', 'fig_curva_cruda.pdf')

# ── FIGURA 2: curva suavizada ────────────────────────────────────────────────
dibujar_curva(suavizar(pred_rf_crudo, horas_eje), suavizar(pred_xgb_crudo, horas_eje),
              'suave', 'fig_curva_suavizada.pdf')

# ── FIGURA scatter real vs predicho (un PDF individual por modelo) ──────────
for nombre, m, color, mslug in [('Random Forest', modelo_rf, '#2563EB', 'rf'),
                                ('XGBoost', modelo_xgb, '#DC2626', 'xgb')]:
    fig, ax = plt.subplots(figsize=figsize(AX_SCATTER))
    ax.scatter(y_tr, m.predict(X_tr), alpha=0.35, s=22, color=color,
               label=f'Train (R²={metricas[nombre]["r2_train"]:.3f})')
    ax.scatter(y_te, m.predict(X_te), alpha=0.85, s=45, color='#F59E0B',
               edgecolors='black', lw=0.3,
               label=f'Test (R²={metricas[nombre]["r2_test"]:.3f}, '
                     f'MAE={metricas[nombre]["mae_test"]:.2f})')
    lim = [0, max(y_final)*1.05]
    ax.plot(lim, lim, 'k--', lw=1.5, label='Ideal (y=x)')
    ax.set_xlim(lim); ax.set_ylim(lim)
    ax.set_xlabel('Real (MPa)', fontsize=FS_LABEL)
    ax.set_ylabel('Predicho (MPa)', fontsize=FS_LABEL)
    ax.tick_params(axis='both', labelsize=FS_TICK)
    leg = ax.legend(fontsize=FS_LEG, loc='upper left', framealpha=0.9, title=nombre)
    leg.get_title().set_fontweight('bold')
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    guardar_pdf(fig, f'fig_scatter_{mslug}.pdf')
    plt.show()

# ── FIGURA importancia de variables (un PDF individual por modelo) ──────────
for nombre, m, mslug in [('Random Forest', modelo_rf, 'rf'),
                         ('XGBoost', modelo_xgb, 'xgb')]:
    fig, ax = plt.subplots(figsize=figsize(AX_IMPORT))
    imp = m.feature_importances_; orden_imp = np.argsort(imp)
    ax.barh([nombres_variables[i] for i in orden_imp], imp[orden_imp],
            color=plt.cm.viridis(np.linspace(0.2, 0.9, len(imp))),
            edgecolor='white', lw=0.5)
    for i, v in enumerate(imp[orden_imp]):
        ax.text(v + imp.max()*0.01, i, f'{v:.3f}', va='center', fontsize=9)
    ax.set_xlabel(f'Importancia — {nombre}', fontsize=FS_LABEL)
    ax.tick_params(axis='both', labelsize=FS_TICK)
    ax.set_xlim(0, imp.max()*1.2); ax.grid(True, alpha=0.25, axis='x')
    plt.tight_layout()
    guardar_pdf(fig, f'fig_importancia_{mslug}.pdf')
    plt.show()

# ══════════════════════════════════════════════════════════════════════════════
# 4. REENTRENAR CON EL 100% PARA EXPORTAR (sin cambios)
# ══════════════════════════════════════════════════════════════════════════════
modelo_rf.fit(X_final, y_final)
modelo_xgb.fit(X_final, y_final)

import joblib, collections
from google.colab import files
combos_validos = collections.defaultdict(list)
for cod_tipo in df['tipo_acelerante'].dropna().unique():
    mask = df['tipo_acelerante'] == cod_tipo
    productos_cod = sorted(df.loc[mask, 'acelerante'].dropna().unique().tolist())
    nombre_tipo = factorizacion['tipo_acelerante'][int(cod_tipo)]
    combos_validos[nombre_tipo] = productos_cod
factor_portable = {k: list(v) for k, v in factorizacion.items()}

def construir_paquete(modelo, tipo):
    return {'modelo_unico': modelo, 'imputer': imputer, 'features_ok': features_ok,
            'medianas': medianas, 'factorizacion': factor_portable,
            'combos_validos': combos_validos, 'tipo': tipo,
            'r2_test': metricas[tipo]['r2_test'] if tipo in metricas else None}

joblib.dump(construir_paquete(modelo_xgb, 'XGBoost'), 'modelo_hormigon_xgb.pkl')
joblib.dump(construir_paquete(modelo_rf,  'Random Forest'), 'modelo_hormigon_rf.pkl')

# ── Descargar SOLO los modelos (las figuras van al ZIP único de la Celda 4) ──
for f in ['modelo_hormigon_xgb.pkl', 'modelo_hormigon_rf.pkl']:
    files.download(f)
print("\n✅ Modelos exportados. Las figuras PDF se empaquetan en el ZIP de la Celda 4.")

# ==============================================================================
# CELDA 3 — REGRESIONES SIMBÓLICAS (gplearn, LASSO, PySR)   ·  versión corregida
# ==============================================================================
# Para cada método:
#   - Tabla de evolución del entrenamiento
#   - Fórmula final renderizada en LaTeX
#   - Gráfico resistencia-tiempo y scatter real vs predicho (apilados)
# PySR añade además las 3 curvas finalistas.
# Requiere haber ejecutado las Celdas 1 y 2 (df, features_ok, X_imp disponibles).
#
# CAMBIOS frente a la versión anterior:
#   1) Split POR MEZCLA (GroupShuffleSplit): ninguna mezcla aparece a la vez en
#      train y test → R² honesto sobre mezclas nuevas (no interpolación de edad).
#      El MISMO split se usa en gplearn, LASSO y PySR.
#   2) Tabla LASSO: muestra R² CV medio real (antes imprimía -MSE bajo ese rótulo).
#   3) Imputación: reutiliza X_imp de la Celda 1 (KNN) en vez de un median local.
#   4) Tiempos de compresión derivados de las columnas presentes (auto 98 d).
#   5) Leyenda de variables filtrada a las que existen en features_ok.
# ==============================================================================
get_ipython().system('pip install gplearn pysr -q')

import numpy as np
import pandas as pd
import sympy as sp
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV, Lasso
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import GroupShuffleSplit, cross_val_score
from IPython.display import display, Math, Markdown
import matplotlib.pyplot as plt

# ── Imputación: usa X_imp ya imputada en las Celdas 1 / 2B ───────────────────
X_imp_local = X_imp                                    # imputada en Celdas 1/2B
if hasattr(X_imp_local, 'columns'):                    # si es DataFrame → ndarray
    X_imp_local = X_imp_local[features_ok].values      # alineado a features_ok
print("Imputación: usando X_imp de las Celdas 1/2B.")

# ── Tiempos de compresión (SIN 98 d) ─────────────────────────────────────────
TIEMPOS_PEN   = [3,6,10,15,20,30,45,60,75,90,105,120,135,150,165,180,195,210,225,240]
TIEMPOS_CLAVO = [4, 6, 8, 10, 12, 20, 24]
TIEMPOS_COMP  = [1, 1.25, 3, 7, 28]   # 98 d excluido a propósito

SERIE_LOCAL = (
    [(t / 60,   f'pen_{t}min',  'Penetración') for t in TIEMPOS_PEN]   +
    [(float(t), f'clavo_{t}h',  'Clavo')       for t in TIEMPOS_CLAVO] +
    [(t * 24,   f'comp_{t}d',   'Compresión')  for t in TIEMPOS_COMP]
)

# ── Aplanado: cada ensayo es (features de su mezcla + tiempo) ────────────────
# `grupo_plano` guarda el id de la mezcla física (fila original) de cada ensayo,
# para que el split posterior NO mezcle la misma muestra entre train y test.
X_plano, y_plano, grupo_plano = [], [], []
for horas, col, serie in SERIE_LOCAL:
    if col not in df.columns:
        continue
    mask = df[col].notna()
    if mask.sum() < 5:
        continue
    X_sub = X_imp_local[mask.values]
    y_sub = df.loc[mask, col].values.astype(float)
    X_plano.append(np.hstack((X_sub, np.full((len(y_sub), 1), horas))))
    y_plano.append(y_sub)
    grupo_plano.append(np.where(mask.values)[0])   # índice de fila = id de mezcla

X_final = np.vstack(X_plano)
y_final = np.concatenate(y_plano)
grupos  = np.concatenate(grupo_plano)
nombres_variables = features_ok + ['tiempo_horas']

# ── Split POR GRUPOS: 80% mezclas entrenan, 20% se reservan para validar ─────
# El mismo split se usa en gplearn, LASSO y PySR. Todos los R² de este cuaderno
# se calculan SOLO sobre X_test/y_test (mezclas nunca vistas en entrenamiento).
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
idx_tr, idx_te = next(gss.split(X_final, y_final, groups=grupos))
X_train, X_test = X_final[idx_tr], X_final[idx_te]
y_train, y_test = y_final[idx_tr], y_final[idx_te]

n_mezclas_tr = len(np.unique(grupos[idx_tr]))
n_mezclas_te = len(np.unique(grupos[idx_te]))
solape = len(set(grupos[idx_tr]) & set(grupos[idx_te]))
assert solape == 0, "FUGA: una mezcla aparece en train y test a la vez"

print(f"Dataset aplanado: {X_final.shape[0]} ensayos × {X_final.shape[1]} variables "
      f"({len(np.unique(grupos))} mezclas)")
print(f"Entrenamiento (80%): {len(idx_tr):>4} ensayos · {n_mezclas_tr} mezclas")
print(f"Validación   (20%): {len(idx_te):>4} ensayos · {n_mezclas_te} mezclas "
      f"← aquí se mide el R²")
print(f"Solape de mezclas entre train y test (fuga): {solape}")

# ── Datos reales de compresión + curva de simulación (compartido) ────────────
dias_comp  = TIEMPOS_COMP
horas_comp = [d * 24 for d in dias_comp]
R_medias   = [df[f'comp_{d}d'].dropna().mean() for d in dias_comp]
R_stds     = [df[f'comp_{d}d'].dropna().std()  for d in dias_comp]
medianas   = np.median(X_final[:, :-1], axis=0)
horas_max  = max(horas_comp)
horas_eje  = np.logspace(np.log10(3/60), np.log10(horas_max), 300)
X_curva    = np.column_stack([np.tile(medianas, (len(horas_eje), 1)), horas_eje])

# Ticks del eje de tiempo (early fijos + días de compresión presentes)
ticks_h   = [3/60, 1, 6] + horas_comp
ticks_lbl = ['3 min', '1 h', '6 h'] + [f'{d:g} d' for d in dias_comp]

# ── Símbolos LaTeX de TODAS las variables usadas (13 features + tiempo) ───────
# Sin variables de temperatura: no forman parte de esta versión del modelo.
SIMBOLOS = {
    'tiempo_horas':        sp.Symbol('t'),
    'material':            sp.Symbol('M'),
    'relacion_ac':         sp.Symbol('AC'),
    'cemento':             sp.Symbol('C'),
    'tipo_acelerante':     sp.Symbol('A_f'),
    'acelerante':          sp.Symbol('A_p'),
    'dosificacion':        sp.Symbol('D'),
    'punto_max_ace_mWg':   sp.Symbol('P_ace'),
    'pendiente_ace_mWgh':  sp.Symbol('m_ace'),
    'energia_ace_Jg':      sp.Symbol('E_ace'),
    'punto_max_ppal_mWg':  sp.Symbol('P_ppal'),
    'pendiente_ppal_mWgh': sp.Symbol('m_ppal'),
    'energia_ppal_Jg':     sp.Symbol('E_ppal'),
    'energia_total':       sp.Symbol('E_tot'),
}

def graficar_curva_y_scatter(nombre, color, res_curva, y_pred_test_m,
                             r2_test_m, mae_m):
    """Genera los 2 gráficos comunes a cada método en figuras SEPARADAS:
    curva resistencia-tiempo (banner) y scatter real vs predicho (cuadrado)."""
    slug = nombre.lower()
    # ── Curva resistencia-tiempo ──
    fig, ax1 = plt.subplots(figsize=figsize(AX_CURVA))
    ax1.plot(horas_eje, np.maximum(res_curva, 0), '-', color=color, lw=3,
             label=f'Fórmula {nombre}')
    ax1.errorbar(horas_comp, R_medias, yerr=R_stds, fmt='ko', ms=7, capsize=4,
                 zorder=5, label='Media ± std lab')
    ax1.set_xscale('log')
    ax1.set_xticks(ticks_h)
    ax1.set_xticklabels(ticks_lbl, fontsize=FS_TICK)
    ax1.set_xlabel('Tiempo (horas) — escala log', fontsize=FS_LABEL)
    ax1.set_ylabel('Resistencia (MPa)', fontsize=FS_LABEL)
    ax1.tick_params(axis='y', labelsize=FS_TICK)
    ax1.legend(fontsize=FS_LEG); ax1.grid(True, which='both', ls='--', alpha=0.3)
    ax1.set_ylim(0, max(R_medias)*1.3)
    plt.tight_layout()
    guardar_pdf(fig, f'simbolica_curva_{slug}.pdf')
    plt.show()
    # ── Scatter real vs predicho (métricas en la leyenda, sin título) ──
    fig, ax2 = plt.subplots(figsize=figsize(AX_SCATTER))
    ax2.scatter(y_test, y_pred_test_m, alpha=0.6, color=color, edgecolor='white', s=50,
                label=f'{nombre}\nR²={r2_test_m:.4f}  MAE={mae_m:.2f} MPa')
    lim = [min(y_test.min(), y_pred_test_m.min()), max(y_test.max(), y_pred_test_m.max())]
    ax2.plot(lim, lim, 'k--', lw=1.5, label='Ideal (y=x)')
    ax2.set_xlim(lim); ax2.set_ylim(lim)
    ax2.set_xlabel('Resistencia Real (MPa)', fontsize=FS_LABEL)
    ax2.set_ylabel('Resistencia Predicha (MPa)', fontsize=FS_LABEL)
    ax2.tick_params(axis='both', labelsize=FS_TICK)
    ax2.legend(fontsize=FS_LEG, loc='upper left', framealpha=0.9); ax2.grid(True, alpha=0.3)
    plt.tight_layout()
    guardar_pdf(fig, f'simbolica_scatter_{slug}.pdf')
    plt.show()

# ── Significado de las variables (las 13 reales + tiempo, en orden) ───────────
# Se construye recorriendo features_ok, así la tabla refleja EXACTAMENTE las
# variables que entran al modelo. Sin temperatura.
DESCRIPCIONES = {  # columna -> (descripción, unidad)
    'material':            ('Material / mortero base (categórica factorizada)',     'código'),
    'relacion_ac':         ('Relación agua/cemento',                                '—'),
    'cemento':             ('Tipo de cemento (categórica factorizada)',             'código'),
    'tipo_acelerante':     ('Familia de acelerante (categórica factorizada)',       'código'),
    'acelerante':          ('Producto acelerante (categórica factorizada)',         'código'),
    'dosificacion':        ('Dosificación de acelerante',                           '%'),
    'punto_max_ace_mWg':   ('Pico de flujo de calor — fase del acelerante',         'mW/g'),
    'pendiente_ace_mWgh':  ('Pendiente de subida — fase del acelerante',            'mW/g·h'),
    'energia_ace_Jg':      ('Energía liberada — fase del acelerante',               'J/g'),
    'punto_max_ppal_mWg':  ('Pico de flujo de calor — fase principal (C₃S)',        'mW/g'),
    'pendiente_ppal_mWgh': ('Pendiente de subida — fase principal',                 'mW/g·h'),
    'energia_ppal_Jg':     ('Energía liberada — fase principal',                    'J/g'),
    'energia_total':       ('Energía total de hidratación',                         'J/g'),
    'tiempo_horas':        ('Tiempo de curado',                                     'h'),
}

orden = features_ok + ['tiempo_horas']   # 13 features reales + el tiempo
filas = []
for col in orden:
    if col not in DESCRIPCIONES:
        continue
    desc, ud = DESCRIPCIONES[col]
    simb_latex = sp.latex(SIMBOLOS.get(col, sp.Symbol(col.replace('_', ''))))
    filas.append(f"| ${simb_latex}$ | `{col}` | {desc} | {ud} |")

tabla_md = ("| Símbolo | Variable | Significado | Unidad |\n"
            "|:--:|:--|:--|:--:|\n" + "\n".join(filas))
display(Markdown("### 📖 Significado de las variables de las ecuaciones\n" + tabla_md))

# ══════════════════════════════════════════════════════════════════════════════
# A) GPLEARN
# ══════════════════════════════════════════════════════════════════════════════
from gplearn.genetic import SymbolicRegressor

print("\n" + "="*70)
print(" 🔬 A) REGRESIÓN SIMBÓLICA — gplearn")
print("="*70)

NODOS_MAX = 25   # tope de nodos que quieres tolerar en la fórmula final

def ajustar_gplearn_con_tope(X_tr, y_tr, nodos_max=NODOS_MAX,
                              parsimony_inicial=0.01, intentos=4):
    """gplearn no tiene un tope DURO de nodos (no existe en su API). Como red
    de seguridad, si el programa ganador supera nodos_max, se reintenta con
    una parsimony_coefficient más alta hasta encajar (o agotar los intentos)."""
    parsimony = parsimony_inicial
    est = None
    for intento in range(intentos):
        est = SymbolicRegressor(
            population_size=500, generations=15,
            function_set=['add','sub','mul','div','sqrt','log','inv'],  # sin sin/cos: sin motivo físico aquí
            metric='mse', parsimony_coefficient=parsimony,
            init_depth=(2, 4),                  # árboles iniciales más compactos (antes (2,6))
            p_crossover=0.65, p_subtree_mutation=0.1,
            p_hoist_mutation=0.15,               # ↑ poda subárboles grandes (antes 0.05)
            p_point_mutation=0.1, max_samples=0.9,
            verbose=1, random_state=42, n_jobs=1,
        )
        est.fit(X_tr, y_tr)
        nodos = est._program.length_
        print(f"  Intento {intento+1}: parsimony={parsimony:.4f} → {nodos} nodos")
        if nodos <= nodos_max:
            return est
        parsimony *= 3   # el efecto de parsimony no es lineal; hay que subir fuerte
    print(f"  ⚠️ No se alcanzó el tope de {nodos_max} nodos tras {intentos} intentos "
          f"(quedó en {nodos}). Sube NODOS_MAX o `intentos` si quieres seguir probando.")
    return est

est_gp = ajustar_gplearn_con_tope(X_train, y_train)

est_gp.fit(X_train, y_train)   # verbose=1 imprime la tabla de evolución por generación

y_pred_gp  = est_gp.predict(X_test)
r2_gp      = r2_score(y_test, y_pred_gp)
mae_gp     = mean_absolute_error(y_test, y_pred_gp)

# Conversión a LaTeX vía sympy
entorno_gp = {
    'add': lambda x,y: x+y, 'sub': lambda x,y: x-y, 'mul': lambda x,y: x*y,
    'div': lambda x,y: x/y, 'sqrt': lambda x: sp.sqrt(sp.Abs(x)),
    'log': lambda x: sp.log(sp.Abs(x)), 'inv': lambda x: 1/x,
    'sin': sp.sin, 'cos': sp.cos,
}
for i, nombre in enumerate(nombres_variables):
    entorno_gp[f'X{i}'] = SIMBOLOS.get(nombre, sp.Symbol(nombre.replace('_','')))
try:
    expr_gp  = eval(str(est_gp._program), {'__builtins__': None}, entorno_gp)
    latex_gp = sp.latex(sp.simplify(expr_gp))
except Exception as e:
    latex_gp = r"\text{(no simplificable)}"
    print(f"  Aviso: {e}")

display(Markdown(f"### 🔬 gplearn — R²={r2_gp:.4f} | MAE={mae_gp:.2f} MPa | "
                 f"{est_gp._program.length_} nodos"))
display(Math(r"R(t) = " + latex_gp))

res_curva_gp = est_gp.predict(X_curva)
graficar_curva_y_scatter('gplearn', '#3B82F6', res_curva_gp, y_pred_gp, r2_gp, mae_gp)


# ══════════════════════════════════════════════════════════════════════════════
# B) LASSO
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "="*70)
print(" 📐 B) REGRESIÓN PARAMÉTRICA — LASSO")
print("="*70)

idx_D = features_ok.index('dosificacion')
idx_P = features_ok.index('punto_max_ppal_mWg')
idx_A = features_ok.index('punto_max_ace_mWg')
idx_t = len(features_ok)

def construir_ladrillos(t, D, P, A):
    return pd.DataFrame({
        't': t, 'ln(t+1)': np.log(t+1), '1/t': 1/(t+1e-5), 'sqrt(t)': np.sqrt(t),
        'D': D, 'P_ppal': P, 'P_ace': A,
        'D*ln(t+1)': D*np.log(t+1), 'P_ppal*ln(t+1)': P*np.log(t+1),
        'D*P_ppal': D*P, 'D/sqrt(t)': D/(np.sqrt(t)+1e-5),
    })

df_lad = construir_ladrillos(X_final[:,idx_t], X_final[:,idx_D],
                             X_final[:,idx_P], X_final[:,idx_A])
nombres_lad = df_lad.columns.tolist()

# MISMO split por grupos que el resto de métodos (df_lad va alineado con X_final)
Xl_tr, Xl_te = df_lad.values[idx_tr], df_lad.values[idx_te]
yl_tr, yl_te = y_final[idx_tr],       y_final[idx_te]
scaler = StandardScaler()
Xl_tr_s = scaler.fit_transform(Xl_tr)
Xl_te_s = scaler.transform(Xl_te)

modelo_lasso = LassoCV(cv=5, max_iter=10000, random_state=42)
modelo_lasso.fit(Xl_tr_s, yl_tr)

pred_lasso_te = np.maximum(modelo_lasso.predict(Xl_te_s), 0)
r2_lasso  = r2_score(yl_te, pred_lasso_te)
mae_lasso = mean_absolute_error(yl_te, pred_lasso_te)

# Tabla de evolución LASSO: R² CV medio real vs alpha (camino de regularización)
print("\nEvolución LASSO — R² medio en CV por valor de alpha (regularización):")
print(f"  {'alpha':>10} {'R² CV medio':>12} {'n features ≠0':>14}")
paso = max(1, len(modelo_lasso.alphas_) // 10)
for a in modelo_lasso.alphas_[::paso]:
    r2_cv = cross_val_score(Lasso(alpha=a, max_iter=10000),
                            Xl_tr_s, yl_tr, cv=5, scoring='r2').mean()
    n_nz  = np.sum(np.abs(Lasso(alpha=a, max_iter=10000)
                          .fit(Xl_tr_s, yl_tr).coef_) > 1e-6)
    print(f"  {a:>10.4f} {r2_cv:>12.4f} {n_nz:>14}")
print(f"\n  → alpha óptimo elegido: {modelo_lasso.alpha_:.4f}")

# Fórmula en escala original → LaTeX
coefs_reales = modelo_lasso.coef_ / scaler.scale_
intercepto   = modelo_lasso.intercept_ - np.sum(coefs_reales * scaler.mean_)
t, D, P_ppal, P_ace = sp.symbols('t D P_ppal P_ace')
map_lad = {
    't': t, 'ln(t+1)': sp.log(t+1), '1/t': 1/t, 'sqrt(t)': sp.sqrt(t),
    'D': D, 'P_ppal': P_ppal, 'P_ace': P_ace,
    'D*ln(t+1)': D*sp.log(t+1), 'P_ppal*ln(t+1)': P_ppal*sp.log(t+1),
    'D*P_ppal': D*P_ppal, 'D/sqrt(t)': D/sp.sqrt(t),
}
expr_lasso = sp.Float(round(intercepto, 3))
print("\nFeatures seleccionados:")
for nombre, coef in zip(nombres_lad, coefs_reales):
    if abs(coef) > 0.001:
        print(f"  {nombre:<18}: {coef:+.4f}")
        expr_lasso += sp.Float(round(coef, 3)) * map_lad[nombre]
latex_lasso = sp.latex(expr_lasso)

display(Markdown(f"### 📐 LASSO — R²={r2_lasso:.4f} | MAE={mae_lasso:.2f} MPa"))
display(Math(r"R(t) = " + latex_lasso))

# Curva de simulación LASSO
df_sim = construir_ladrillos(horas_eje,
    np.full_like(horas_eje, np.median(X_final[:,idx_D])),
    np.full_like(horas_eje, np.median(X_final[:,idx_P])),
    np.full_like(horas_eje, np.median(X_final[:,idx_A])))
res_curva_lasso = np.maximum(modelo_lasso.predict(scaler.transform(df_sim.values)), 0)
graficar_curva_y_scatter('LASSO', '#10B981', res_curva_lasso,
                         pred_lasso_te, r2_lasso, mae_lasso)


# ══════════════════════════════════════════════════════════════════════════════
# C) PySR
# ══════════════════════════════════════════════════════════════════════════════
from pysr import PySRRegressor

print("\n" + "="*70)
print(" 🔬 C) REGRESIÓN SIMBÓLICA — PySR (~3-5 min)")
print("="*70)

X_train_df = pd.DataFrame(X_train, columns=nombres_variables)
X_test_df  = pd.DataFrame(X_test,  columns=nombres_variables)

modelo_pysr = PySRRegressor(
    binary_operators=['+','-','*','/'], unary_operators=['sqrt','log','sin','cos'],
    niterations=50, populations=20, population_size=50,
    parsimony=0.01, maxsize=25, random_state=42, procs=1,
    batching=True, batch_size=50, verbosity=0,
)
modelo_pysr.fit(X_train_df, y_train)

# Tabla de evolución PySR (todas las ecuaciones del frente de Pareto)
r2_todas = np.array([r2_score(y_test, modelo_pysr.predict(X_test_df, index=i))
                     for i in range(len(modelo_pysr.equations_))])
mae_todas = np.array([mean_absolute_error(y_test, modelo_pysr.predict(X_test_df, index=i))
                      for i in range(len(modelo_pysr.equations_))])
complejidades = modelo_pysr.equations_['complexity'].values

print("\nEvolución PySR — frente de Pareto (todas las ecuaciones):")
print(f"  {'ID':<3} {'Nodos':<6} {'R² Test':<9} {'MAE':<9} {'Ecuación'}")
print("  " + "-"*70)
for i in range(len(modelo_pysr.equations_)):
    eq_str = str(modelo_pysr.equations_.iloc[i]['equation'])
    if len(eq_str) > 35: eq_str = eq_str[:32] + "..."
    print(f"  {i:<3} {complejidades[i]:<6} {r2_todas[i]:<9.4f} {mae_todas[i]:<9.2f} {eq_str}")

# Seleccionar 3 finalistas (índices distintos garantizados)
n_eq = len(modelo_pysr.equations_)
idx_baja, idx_alta = 0, n_eq - 1
idx_media = max(idx_baja+1, min(n_eq//2, idx_alta-1)) if n_eq > 2 else idx_baja
if n_eq > 1:
    mejoras  = np.nan_to_num(np.diff(r2_todas) / np.maximum(np.diff(complejidades), 1))
    idx_codo = int(np.argmax(mejoras))
else:
    idx_codo = 0

seleccion = [(idx_baja, 'Baja', '#F59E0B'),
             (idx_media, 'Media', '#10B981'),
             (idx_alta, 'Alta (mejor)', '#8B5CF6')]

# LaTeX de las 3 finalistas
display(Markdown("### 🔬 PySR — 3 ecuaciones finalistas:"))
for idx, nombre, color in seleccion:
    nodos = int(complejidades[idx])
    es_codo = " ⭐" if idx == idx_codo else ""
    try:
        latex_p = sp.latex(sp.simplify(modelo_pysr.sympy(index=idx)))
    except Exception:
        latex_p = r"\text{(no simplificable)}"
    display(Markdown(f"<span style='color:{color}'>**{nombre}**</span> — "
                     f"{nodos} nodos | R²={r2_todas[idx]:.4f} | MAE={mae_todas[idx]:.2f}{es_codo}"))
    display(Math(r"R(t) = " + latex_p))

# Gráfico PySR: curva temporal (3 curvas) y scatter, en figuras SEPARADAS
X_curva_df = pd.DataFrame(X_curva, columns=nombres_variables)
fig, ax1 = plt.subplots(figsize=figsize(AX_CURVA))
for idx, nombre, color in seleccion:
    res_i = np.maximum(modelo_pysr.predict(X_curva_df, index=idx), 0)
    lw = 3 if idx == idx_codo else 2
    ax1.plot(horas_eje, res_i, '-', color=color, lw=lw,
             label=f'Eq {idx} ({nombre})' + (' ⭐' if idx == idx_codo else ''))
ax1.errorbar(horas_comp, R_medias, yerr=R_stds, fmt='ko', ms=7, capsize=4,
             zorder=5, label='Media ± std lab')
ax1.set_xscale('log')
ax1.set_xticks(ticks_h)
ax1.set_xticklabels(ticks_lbl, fontsize=FS_TICK)
ax1.set_xlabel('Tiempo (horas) — escala log', fontsize=FS_LABEL)
ax1.set_ylabel('Resistencia (MPa)', fontsize=FS_LABEL)
ax1.tick_params(axis='y', labelsize=FS_TICK)
ax1.legend(fontsize=FS_LEG); ax1.grid(True, which='both', ls='--', alpha=0.3)
ax1.set_ylim(0, max(R_medias)*1.35)
plt.tight_layout()
guardar_pdf(fig, 'simbolica_curva_pysr.pdf')
plt.show()

fig, ax2 = plt.subplots(figsize=figsize(AX_SCATTER))
for idx, nombre, color in seleccion:
    yp = modelo_pysr.predict(X_test_df, index=idx)
    ax2.scatter(y_test, yp, alpha=0.5, color=color, s=45,
                label=f'Eq {idx} (R²={r2_todas[idx]:.3f})')
lim = [min(y_test), max(y_test)]
ax2.plot(lim, lim, 'k--', lw=1.5, label='Ideal (y=x)')
ax2.set_xlim(lim); ax2.set_ylim(lim)
ax2.set_xlabel('Resistencia Real (MPa)', fontsize=FS_LABEL)
ax2.set_ylabel('Resistencia Predicha (MPa)', fontsize=FS_LABEL)
ax2.tick_params(axis='both', labelsize=FS_TICK)
ax2.legend(fontsize=FS_LEG, loc='upper left', framealpha=0.9); ax2.grid(True, alpha=0.3)
plt.tight_layout()
guardar_pdf(fig, 'simbolica_scatter_pysr.pdf')
plt.show()



# ══════════════════════════════════════════════════════════════════════════════
# TABLA COMPARATIVA FINAL
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "="*70)
print(" 📊 COMPARATIVA FINAL DE MÉTODOS SIMBÓLICOS  (R² sobre el 20% de validación)")
print("="*70)
print(f"  {'Método':<22} {'R² Test':>9} {'MAE (MPa)':>11}")
print("  " + "-"*44)
print(f"  {'gplearn':<22} {r2_gp:>9.4f} {mae_gp:>11.2f}")
print(f"  {'LASSO':<22} {r2_lasso:>9.4f} {mae_lasso:>11.2f}")
print(f"  {'PySR (mejor)':<22} {r2_todas[idx_alta]:>9.4f} {mae_todas[idx_alta]:>11.2f}")
print("="*70)

# ==============================================================================
# CELDA 4 — MODELOS FÍSICOS (Hansen / Gompertz) + NORMA CE-21 (rango válido ≥1 d)
# Figuras separadas, tamaño A4 horizontal, sin títulos, sin anotaciones n=,
# exportadas a PDF vectorial para LaTeX.
# ==============================================================================
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
from scipy.optimize import curve_fit
from sklearn.metrics import r2_score, mean_absolute_error
from IPython.display import display, Math, Markdown

# ── Paleta ───────────────────────────────────────────────────────────────────
C_PEN, C_CLA, C_COM = '#3B82F6', '#10B981', '#EF4444'
C_HANSEN, C_GOMP    = '#8B5CF6', '#F59E0B'
C_CE21              = '#475569'

# Tamaños y fuentes: se heredan del sistema unificado de la Celda 1
# (AX_CURVA, AX_SCATTER, FS_*, figsize(), guardar_pdf()).

# ── 1. Ecuaciones físicas ────────────────────────────────────────────────────
def modelo_hansen(t, R_max, tau, beta):
    t_safe = np.maximum(t, 1e-5)
    return R_max * np.exp(-(tau / t_safe)**beta)

def modelo_gompertz(t, R_max, k, lam):
    return R_max * np.exp(-k * np.exp(-lam * t))

def curva_ce21(horas, res_28d, tipo_cemento='R'):
    """
    CE-21 βcc(t)=exp(s·(1-√(28/t_días))) anclada a 28 d.
    SOLO definida para t ≥ 1 día (rango normativo). Antes de 1 d devuelve NaN
    (no se extrapola): la norma no modela edades tempranas.
    """
    s = {'R': 0.20, 'N': 0.25, 'S': 0.38}.get(tipo_cemento, 0.20)
    horas = np.asarray(horas, dtype=float)
    dias  = horas / 24.0
    with np.errstate(divide='ignore', invalid='ignore'):
        beta = np.where(dias >= 1.0,
                        np.exp(s * (1.0 - np.sqrt(28.0 / np.maximum(dias, 1e-9)))),
                        np.nan)
    return res_28d * beta   # NaN < 1 día

# ── 2. Preparar datos ────────────────────────────────────────────────────────
TIEMPOS_PEN   = [3,6,10,15,20,30,45,60,75,90,105,120,135,150,165,180,195,210,225,240]
TIEMPOS_CLAVO = [4, 6, 8, 10, 12, 20, 24]
TIEMPOS_COMP  = [1, 1.25, 3, 7, 28]

SERIE = (
    [(t / 60,   f'pen_{t}min', 'Penetración', C_PEN) for t in TIEMPOS_PEN]  +
    [(float(t), f'clavo_{t}h', 'Clavo',       C_CLA) for t in TIEMPOS_CLAVO]+
    [(t * 24,   f'comp_{t}d',  'Compresión',  C_COM) for t in TIEMPOS_COMP]
)

horas_aj, R_medias, R_stds, series, n_aj = [], [], [], [], []
horas_ind, R_ind = [], []
for horas, col, serie, color in SERIE:
    if col not in df.columns:
        continue
    vals = df[col].dropna()
    if len(vals) < 5:
        continue
    horas_aj.append(horas); R_medias.append(vals.mean())
    R_stds.append(vals.std()); series.append(serie); n_aj.append(len(vals))
    horas_ind.extend([horas] * len(vals))
    R_ind.extend(vals.values.tolist())

horas_aj = np.array(horas_aj); R_medias = np.array(R_medias)
R_stds   = np.array(R_stds);   series   = np.array(series); n_aj = np.array(n_aj)
horas_ind = np.array(horas_ind); R_ind = np.array(R_ind)

MODO_AJUSTE = 'individual'
if MODO_AJUSTE == 'individual':
    x_fit, y_fit, sigma_fit = horas_ind, R_ind, None
elif MODO_AJUSTE == 'media_ponderada':
    sig = np.where(R_stds > 0, R_stds, np.nanmin(R_stds[R_stds > 0]))
    x_fit, y_fit, sigma_fit = horas_aj, R_medias, sig
else:
    x_fit, y_fit, sigma_fit = horas_aj, R_medias, None

print(f"Modo de ajuste: '{MODO_AJUSTE}'  →  {len(x_fit)} puntos para curve_fit "
      f"({horas_aj.min()*60:.0f} min → {horas_aj.max()/24:.0f} días)")

# ── 3. Ajuste de curvas ──────────────────────────────────────────────────────
R_top = R_ind.max()
popt_h, pcov_h = curve_fit(modelo_hansen, x_fit, y_fit, p0=[R_top*1.5, 1.0, 0.5],
                           sigma=sigma_fit, absolute_sigma=(sigma_fit is not None),
                           bounds=([R_top*0.8, 0.001, 0.05], [R_top*4.0, 50.0, 5.0]),
                           maxfev=20000)
popt_g, pcov_g = curve_fit(modelo_gompertz, x_fit, y_fit, p0=[R_top*1.5, 5.0, 0.05],
                           sigma=sigma_fit, absolute_sigma=(sigma_fit is not None),
                           bounds=([R_top*0.8, 0.1, 0.001], [R_top*4.0, 50.0, 10.0]),
                           maxfev=20000)
perr_h = np.sqrt(np.diag(pcov_h)); perr_g = np.sqrt(np.diag(pcov_g))

TIPO_CEMENTO = 'R'
res_28  = R_medias[-1]
s_ce21  = {'R': 0.20, 'N': 0.25, 'S': 0.38}[TIPO_CEMENTO]

# ── 4. Métricas (CE-21 SOLO en su rango válido ≥1 día) ───────────────────────
pred_h  = modelo_hansen(x_fit, *popt_h)
pred_g  = modelo_gompertz(x_fit, *popt_g)
pred_ce = curva_ce21(x_fit, res_28, TIPO_CEMENTO)
mask_ce = ~np.isnan(pred_ce)                      # puntos ≥1 día

r2_h, mae_h   = r2_score(y_fit, pred_h),  mean_absolute_error(y_fit, pred_h)
r2_g, mae_g   = r2_score(y_fit, pred_g),  mean_absolute_error(y_fit, pred_g)
r2_ce  = r2_score(np.asarray(y_fit)[mask_ce], pred_ce[mask_ce])
mae_ce = mean_absolute_error(np.asarray(y_fit)[mask_ce], pred_ce[mask_ce])

print("\n=== CONSTANTES FÍSICAS AJUSTADAS ===")
print(f"Hansen:   R_max={popt_h[0]:.2f}±{perr_h[0]:.2f} | τ={popt_h[1]:.3f} | β={popt_h[2]:.4f}")
print(f"Gompertz: R_max={popt_g[0]:.2f}±{perr_g[0]:.2f} | k={popt_g[1]:.3f} | λ={popt_g[2]:.5f}")
print(f"CE-21:    R_28={res_28:.2f} | s={s_ce21} (tipo {TIPO_CEMENTO}, evaluado en {mask_ce.sum()} pts ≥1 d)")
print(f"\n  {'Modelo':<14} {'R²':>9} {'MAE (MPa)':>11}")
print("  " + "-"*36)
print(f"  {'Hansen':<14} {r2_h:>9.4f} {mae_h:>11.2f}")
print(f"  {'Gompertz':<14} {r2_g:>9.4f} {mae_g:>11.2f}")
print(f"  {'CE-21 (≥1 d)':<14} {r2_ce:>9.4f} {mae_ce:>11.2f}")

# ── 5. Ecuaciones en LaTeX ───────────────────────────────────────────────────
t = sp.Symbol('t')
R_max_h, tau_h, beta_h = [round(v, 3) for v in popt_h]
R_max_g, k_g, lam_g    = round(popt_g[0],2), round(popt_g[1],3), round(popt_g[2],5)
eq_hansen   = sp.Float(R_max_h) * sp.exp(-(sp.Float(tau_h)/t)**sp.Float(beta_h))
eq_gompertz = sp.Float(R_max_g) * sp.exp(-sp.Float(k_g) * sp.exp(-sp.Float(lam_g)*t))

display(Markdown("### 🧪 Ecuaciones físicas ajustadas"))
display(Markdown(f"**🟣 Hansen** — R²={r2_h:.4f} | MAE={mae_h:.2f} MPa"))
display(Math(r"R(t) = " + sp.latex(eq_hansen)))
display(Markdown(f"**🟠 Gompertz** — R²={r2_g:.4f} | MAE={mae_g:.2f} MPa"))
display(Math(r"R(t) = " + sp.latex(eq_gompertz)))
display(Markdown(f"**⚪ CE-21** (cemento {TIPO_CEMENTO}, t ≥ 1 día) — R²={r2_ce:.4f} | MAE={mae_ce:.2f} MPa"))
display(Math(
    rf"R(t) = {res_28:.1f} \cdot \exp\!\left[{s_ce21}\left(1 - "
    rf"\sqrt{{\dfrac{{28}}{{t_{{\text{{días}}}}}}}}\right)\right]\quad (t \geq 1\,\text{{día}})"))

# ══════════════════════════════════════════════════════════════════════════════
# FIGURA A — curvas físicas + CE-21 (A4 horizontal, sin título, sin n=)
# ══════════════════════════════════════════════════════════════════════════════
h_fino = np.logspace(np.log10(horas_aj.min()*0.8), np.log10(horas_aj.max()*1.2), 400)
curva_norma = curva_ce21(h_fino, res_28, TIPO_CEMENTO)  # NaN <1 d → la línea arranca en 1 d

plt.close('all')
fig, ax = plt.subplots(figsize=figsize(AX_CURVA))
ax.plot(h_fino, modelo_hansen(h_fino, *popt_h), '-', color=C_HANSEN, lw=2.8,
        label=f'Hansen   ·  R²={r2_h:.3f}  MAE={mae_h:.2f}')
ax.plot(h_fino, modelo_gompertz(h_fino, *popt_g), '-', color=C_GOMP, lw=2.8,
        label=f'Gompertz ·  R²={r2_g:.3f}  MAE={mae_g:.2f}')
ax.plot(h_fino, curva_norma, '--', color=C_CE21, lw=2.4,
        label=f'CE-21 ({TIPO_CEMENTO}, ≥1 d) ·  R²={r2_ce:.3f}  MAE={mae_ce:.2f}')
for serie, col_s in [('Penetración', C_PEN), ('Clavo', C_CLA), ('Compresión', C_COM)]:
    m = series == serie
    ax.errorbar(horas_aj[m], R_medias[m], yerr=R_stds[m], fmt='o', color=col_s,
                ms=8, capsize=4, capthick=1.3, markeredgecolor='white',
                markeredgewidth=0.9, zorder=6, label=f'Lab {serie}')
ax.set_xscale('log')
ax.set_xticks([3/60, 1, 4, 24, 72, 168, 672])
ax.set_xticklabels(['3 min', '1 h', '4 h', '1 d', '3 d', '7 d', '28 d'])
ax.set_xlabel('Tiempo (horas) — escala log', fontsize=FS_LABEL)
ax.set_ylabel('Resistencia (MPa)', fontsize=FS_LABEL)
ax.tick_params(axis='both', labelsize=FS_TICK)
ax.set_ylim(0, R_medias.max() * 1.3)
ax.legend(fontsize=FS_LEG, ncol=2, framealpha=0.9)
ax.grid(True, which='both', ls='--', alpha=0.3)
plt.tight_layout()
guardar_pdf(fig, 'fig_modelos_fisicos.pdf')   # vectorial
plt.show()

# ══════════════════════════════════════════════════════════════════════════════
# FIGURA B — scatter real vs predicho (cuadrado, cabe en A4 horizontal)
# ══════════════════════════════════════════════════════════════════════════════
plt.close('all')
fig, ax = plt.subplots(figsize=figsize(AX_SCATTER))
y_arr = np.asarray(y_fit)
muchos = len(y_arr) > 40
s_sc, a_sc, ew = (26, 0.45, 0.3) if muchos else (80, 0.85, 0.8)

ax.scatter(y_arr, pred_h, color=C_HANSEN, alpha=a_sc, s=s_sc, edgecolors='white',
           lw=ew, zorder=4, label=f'Hansen   ·  R²={r2_h:.3f}  MAE={mae_h:.2f}')
ax.scatter(y_arr, pred_g, color=C_GOMP, alpha=a_sc, s=s_sc, marker='s', edgecolors='white',
           lw=ew, zorder=4, label=f'Gompertz ·  R²={r2_g:.3f}  MAE={mae_g:.2f}')
ax.scatter(y_arr[mask_ce], pred_ce[mask_ce], color=C_CE21, alpha=a_sc, s=s_sc, marker='^',
           edgecolors='white', lw=ew, zorder=4,
           label=f'CE-21 (≥1 d) ·  R²={r2_ce:.3f}  MAE={mae_ce:.2f}')

allv = np.concatenate([y_arr, pred_h, pred_g, pred_ce[mask_ce]])
lim  = [allv.min() * 0.9, allv.max() * 1.08]
ax.plot(lim, lim, 'k--', lw=1.5, zorder=2, label='Ideal (y=x)')
x_banda = np.linspace(lim[0], lim[1], 2)
ax.fill_between(x_banda, x_banda - 2, x_banda + 2, color='gray', alpha=0.12,
                zorder=1, label='Banda ±2 MPa')
ax.set_xlim(lim); ax.set_ylim(lim)
etiq_x = ('Resistencia real — probetas individuales (MPa)' if muchos
          else 'Resistencia real — media laboratorio (MPa)')
ax.set_xlabel(etiq_x, fontsize=FS_LABEL)
ax.set_ylabel('Resistencia predicha (MPa)', fontsize=FS_LABEL)
ax.tick_params(axis='both', labelsize=FS_TICK)
ax.legend(fontsize=FS_LEG, loc='upper left', framealpha=0.9)
ax.grid(True, alpha=0.3)
plt.tight_layout()
guardar_pdf(fig, 'fig_precision_fisicos.pdf')  # vectorial
plt.show()

# ══════════════════════════════════════════════════════════════════════════════
# EMPAQUETAR TODAS LAS FIGURAS DEL CUADERNO EN UN ÚNICO ZIP
# ══════════════════════════════════════════════════════════════════════════════
# Recoge todos los PDF registrados con guardar_pdf() en las Celdas 2, 2.B, 3 y 4.
# Requiere haber ejecutado esas celdas en la misma sesión.
import os, zipfile
from google.colab import files

pdfs_existentes = [p for p in FIGURAS_PDF if os.path.exists(p)]
nombre_zip = 'figuras_tfg.zip'
with zipfile.ZipFile(nombre_zip, 'w', zipfile.ZIP_DEFLATED) as zf:
    for p in pdfs_existentes:
        zf.write(p)

print(f"\n✅ {len(pdfs_existentes)} figuras PDF empaquetadas en '{nombre_zip}':")
for p in pdfs_existentes:
    print(f"   · {p}")
faltan = [p for p in FIGURAS_PDF if not os.path.exists(p)]
if faltan:
    print("\n⚠️ Registradas pero no encontradas en disco (¿celda no ejecutada?):")
    for p in faltan:
        print(f"   · {p}")

files.download(nombre_zip)